import {defineField, defineType} from 'sanity'
import {ComponentIcon} from '@sanity/icons'
import {seoFields} from './shared/seoFields'

export const studio = defineType({
  name: 'studio',
  title: 'Studio',
  type: 'document',
  icon: ComponentIcon,
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'media', title: 'Media'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Studio Name',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'URL Slug',
      type: 'slug',
      group: 'content',
      options: {source: 'title', maxLength: 96},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'tagline',
      title: 'Tagline',
      type: 'string',
      group: 'content',
    }),
    defineField({
      name: 'purpose',
      title: 'Overview',
      type: 'text',
      rows: 3,
      group: 'content',
      description: 'Overview paragraph shown on the individual studio page and the studios overview page.',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Specializations',
      type: 'blockContent',
      group: 'content',
      description: 'List of specializations only — each item should be a bold title.',
    }),
    defineField({
      name: 'industriesServed',
      title: 'Industries Served',
      type: 'array',
      of: [{type: 'string'}],
      group: 'content',
    }),
    defineField({
      name: 'whatWeDoNot',
      title: 'What This Studio Does NOT Do',
      type: 'array',
      of: [{type: 'string'}],
      group: 'content',
    }),
    defineField({
      name: 'heroMediaType',
      title: 'Studio Page — Hero Media Type',
      type: 'string',
      group: 'media',
      options: {
        list: [
          {title: 'Image', value: 'image'},
          {title: 'Video', value: 'video'},
        ],
        layout: 'radio',
      },
      initialValue: 'image',
      description: 'Choose whether the hero frame on the individual studio page shows an image or a video.',
    }),
    defineField({
      name: 'heroImage',
      title: 'Studio Page — Hero Image',
      type: 'image',
      options: {hotspot: true},
      group: 'media',
      description: 'Full-width image for the top of the individual studio page.',
      hidden: ({document}) => document?.heroMediaType === 'video',
      fields: [
        defineField({
          name: 'alt',
          type: 'string',
          title: 'Alt Text',
        }),
        defineField({name: 'roundCrop', type: 'boolean', title: 'Round Crop', description: 'Display this image with a circular crop', initialValue: false}),
      ],
    }),
    defineField({
      name: 'heroVideo',
      title: 'Studio Page — Hero Video (Upload)',
      type: 'file',
      options: {accept: 'video/*'},
      group: 'media',
      description: 'Upload a video file for the top of the individual studio page. Takes priority over the Hero Video URL below.',
      hidden: ({document}) => document?.heroMediaType !== 'video',
    }),
    defineField({
      name: 'heroVideoUrl',
      title: 'Studio Page — Hero Video URL',
      type: 'url',
      group: 'media',
      description: 'Alternative to uploading a file above — a direct link to a video file. Ignored if a video is uploaded above.',
      hidden: ({document}) => document?.heroMediaType !== 'video',
    }),
    defineField({
      name: 'showcaseVideo',
      title: 'Studio Page — Showcase Video (Upload)',
      type: 'file',
      options: {accept: 'video/*'},
      group: 'media',
      description: 'Upload a video for the showcase section above the Projects grid on this studio\'s page. Takes priority over the URL below. Leave both empty to hide the section entirely.',
    }),
    defineField({
      name: 'showcaseVideoUrl',
      title: 'Studio Page — Showcase Video URL',
      type: 'url',
      group: 'media',
      description: 'Alternative to uploading a file above — a YouTube/Vimeo link (embeds as a player) or a direct link to a video file. Ignored if a video is uploaded above. Prefer YouTube/Vimeo over uploading large files to avoid bandwidth cost.',
    }),
    defineField({
      name: 'displayOrder',
      title: 'Display Order',
      type: 'number',
      group: 'content',
      validation: (rule) => rule.required().integer().min(0),
    }),
    ...seoFields,
  ],
  orderings: [
    {
      title: 'Display Order',
      name: 'displayOrderAsc',
      by: [{field: 'displayOrder', direction: 'asc'}],
    },
  ],
  preview: {
    select: {title: 'title', subtitle: 'tagline', media: 'heroImage'},
  },
})
